{
 "title": "Microservices Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Orders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Orders Confirmation Rate (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(orders_confirmation_duration_seconds_sum[5m]) / rate(orders_confirmation_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orders Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "orders_total_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Orders Gauge",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(orders_pending_count / orders_total_count) * 100",
     "legendFormat": "Pending Orders"
    },
    {
     "expr": "(orders_confirmed_count / orders_total_count) * 100",
     "legendFormat": "Confirmed Orders"
    }
   ]
  },
  {
   "title": "Orders Price (avg)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(orders_price_sum[5m])) / sum(rate(orders_price_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orders Confirmation Avg (seconds)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(orders_confirmation_duration_seconds_sum[5m])) / sum(rate(orders_confirmation_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orders Creation Duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(orders_creation_duration_milliseconds_sum[5m])) / sum(rate(orders_creation_duration_milliseconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Basket Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Carrinhos Criados",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(baskets_created_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carrinhos Criados",
   "type": "stat",
   "description": "Total de carrinhos criados",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(baskets_created_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantidade de Produtos por Carrinho",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(baskets_products_quantity_sum[5m])) / sum(rate(baskets_products_quantity_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Baskets by City (s)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(baskets_created_total[5m])) by (city)",
     "legendFormat": "{{city}}"
    }
   ]
  },
  { "title": "Product Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Product Imports Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(products_import_duration_seconds_sum[5m]) / rate(products_import_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Product Imports",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 30 },
   "targets": [
    { "expr": "products_imports_active_count", "legendFormat": "__auto" }
   ]
  }
 ]
}