services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: ms-otel-collector
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
    networks:
      - microservices

  prometheus:
    image: prom/prometheus
    container_name: ms-prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
    ports:
      - 9090:9090
    networks:
      - microservices

  grafana:
    image: grafana/grafana
    container_name: ms-grafana
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - microservices
  
  loki:
    image: grafana/loki:main
    container_name: ms-loki
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/loki-config.yaml
    networks:
      - microservices

  tempo:
    image: grafana/tempo:latest
    container_name: ms-tempo
    command: [ "-config.file=/etc/tempo-config.yaml" ]
    volumes:
      - ./config/tempo-config.yaml:/etc/tempo-config.yaml
    ports:
      - "3200:3200"   # tempo
      - "4317"  # otlp grpc
    networks:
      - microservices
  
  influxdb:
    image: influxdb:1.8
    container_name: ms-influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    networks:
      - microservices
      - k6

volumes:
  grafana-data:
    name: ms-grafana-data

networks:
  microservices:
  k6:
