services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: ms-otel-collector
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
    networks:
      - microservices

  prometheus:
    image: prom/prometheus
    container_name: ms-prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
    ports:
      - 9090:9090
    networks:
      - microservices

  grafana:
    image: grafana/grafana
    container_name: ms-grafana
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - microservices

  seq:
    image: datalust/seq
    container_name: ms-seq
    ports:
      - "5000:80"
      - "5341:5341"
    environment:
      ACCEPT_EULA: Y
    volumes:
      - seq-data:/data
    networks:
      - microservices

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ms-jaeger
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - microservices
  
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: ms-zipkin
    environment:
      - JAVA_OPTS=-Xms1024m -Xmx1024m -XX:+ExitOnOutOfMemoryError
    restart: always
    ports:
      - "9411:9411"
    networks:
      - microservices

volumes:
  seq-data:
    name: ms-seq-data
  grafana-data:
    name: ms-grafana-data

networks:
  microservices:
    driver: bridge
