global:
  smtp_smarthost: sandbox.smtp.mailtrap.io:587
  smtp_from: ${SMTP_FROM}
  smtp_auth_username: ${SMTP_USER}
  smtp_auth_password: ${SMTP_PASSWORD}
  
route:
  group_by: ['alertname']
  group_interval: 5m
  group_wait: 30s
  receiver: 'email'
  repeat_interval: 3h

receivers:

  - name: 'email'
    email_configs:
    - to: ${SMTP_TO}
      send_resolved: true