apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-consumer
  labels:
    app: orders-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-consumer
  template:
    metadata:
      labels:
        app: orders-consumer
    spec:
      containers:
        - name: orders-consumer-container
          image: orders-consumer:v4
          env:
            - name: KAFKA__BOOTSTRAPSERVERS
              value: kafka.default.svc.cluster.local:9092
          livenessProbe:
            exec:
              command:
                - cat
                - /app/healthy
            initialDelaySeconds: 10
            periodSeconds: 5
