global:
  smtp_smarthost: sandbox.smtp.mailtrap.io:587
  smtp_from: tfsantosbr@gmail.com
  smtp_auth_username: b9d14bc214c076
  smtp_auth_password: 3d7a402c6a6c5c
  
route:
  group_by: ['alertname']
  group_interval: 5m
  group_wait: 30s
  receiver: 'email'
  repeat_interval: 3h

receivers:

  - name: 'email'
    email_configs:
    - to: tfsantosbr@gmail.com
      send_resolved: true